services:

  geoserver:
    image: kartoza/geoserver
    container_name: moderate-solar-cadastre-geoserver
    ports:
      - "23000:8080"
    environment:
      - GEOSERVER_ADMIN_USER=admin
      - GEOSERVER_ADMIN_PASSWORD=Moderate2024* # FIXME mover a un .env
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  backend:
    build: ./Backend-Moderate
    container_name: moderate-solar-cadastre-backend
    # command: gunicorn django_backend.wsgi:application --bind 0.0.0.0:8000
    # volumes:
    #   - ./Backend-Moderate:/app
    ports:
      - "23001:8000"

  frontend:
    build: ./Frontend-Moderate
    container_name: moderate-solar-cadastre-frontend
    # volumes:
    #   - ./frontend:/app
    ports:
      - "23002:80"
    command: [nginx-debug, '-g', 'daemon off;']


  # app:

  #   container_name: moderate-solar-cadastre
  #   build: .
  #   image: moderate-solar-cadastre-app:0.0
  #   ports:
  #     - 23001:8000
  #   volumes:
  #     - .:/app
  #     - /sys/fs/cgroup:/sys/fs/cgroup:ro
  #   tty: true
  #   stdin_open: true
  #   entrypoint: bash
  #   privileged: true
  #   restart: always

  # tomcat:
  #   container_name: tomcat
  #   image: tomcat:9.0.98-jdk21-corretto
  #   ports:
  #     - 23000:8080

volumes:
  geoserver_data:


