services:

  backend:
    build: ./Backend-Moderate
    container_name: moderate-solar-cadastre-backend
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
    environment:
      - GEOSERVER_URL=${GEOSERVER_URL}

  frontend:
    build: 
      context: ./Frontend-Moderate
      args:
        ARCGIS_TOKEN: ${ARCGIS_TOKEN}
    container_name: moderate-solar-cadastre-frontend
    # volumes:
    #   - ./frontend:/app
    ports:
      - "${DOCKER_FRONTEND_PORT}:80"
    command: [ nginx-debug, '-g', 'daemon off;' ]
    environment:
      - GEOSERVER_URL=${GEOSERVER_URL}

volumes:
  geoserver_data:


