services:

  geoserver:
    image: kartoza/geoserver
    container_name: moderate-solar-cadastre-geoserver
    ports:
      - "23000:8080"
    environment:
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
    volumes:
      - geoserver_data:/opt/geoserver/data_dir

  postgis:
    image: postgis/postgis:14-3.5-alpine
    container_name: moderate-solar-cadastre-postgis
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      # port:
      # - "${DB_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Backend-Moderate
      dockerfile: Dockerfile
    container_name: moderate-solar-cadastre-backend
    volumes:
      - ./Backend-Moderate:/app
    ports:
      - "${DOCKER_BACKEND_PORT}:8000"
      # - "23003:5432"
    environment:
      - GEOSERVER_URL=${GEOSERVER_URL}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}

  frontend:
    build:
      context: ./Frontend-Moderate
      dockerfile: Dockerfile.dev
      args:
        - ARCGIS_TOKEN=${ARCGIS_TOKEN}
    container_name: moderate-solar-cadastre-frontend
    volumes:
      - ./Frontend-Moderate:/app
      - /app/node_modules
    ports:
      - "${DOCKER_FRONTEND_PORT}:4200"
    environment:
      - NODE_ENV=development

volumes:
  geoserver_data:


