FROM node:20.13

ARG ARCGIS_TOKEN

WORKDIR /app

COPY package*.json ./

RUN npm install -g @angular/cli@latest
RUN npm install

COPY . .

RUN sed -i "s|__TOKEN__|${ARCGIS_TOKEN}|g" src/environments/environment.ts

# RUN npm run build --prod

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]