# Generated by Django 3.2.23 on 2023-11-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=20)),
                ('min_value', models.IntegerField()),
                ('max_value', models.IntegerField()),
            ],
        ),
    ]
