# Generated by Django 3.2.23 on 2023-11-20 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculation_test_v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranges',
            new_name='Profile',
        ),
    ]
